apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resourceNames: ["{{ .Release.Name }}-{{ .Chart.Name }}-auth"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
