{{ if eq .Values.auth.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-auth"
type: Opaque
stringData:
  TS_AUTHKEY: "{{ .Values.auth.key }}"
{{ end }}
