name: Container Images

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/container.yml
      - containers/**

jobs:

  Build_Push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - tailscale-derp
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat TAILSCALE_VERSION)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v4
        with:
          context: containers/${{ matrix.container }}
          push: true
          tags: |
            sspreitzer/${{ matrix.container }}:latest
            sspreitzer/${{ matrix.container }}:${{ steps.getversion.outputs.version }}
